week 1 assignment

In [66]:
import pandas as pd
import numpy as np
from scipy.ndimage import zoom
import unittest

1.1 [1 pt] Please write a function called computation that takes three variables called a(integer), v1(vector represented as a list) and v2(vector represented as a list) and returns a dictionary that has six keys: addition (the sum of v1 and v2, this should be a numpy array), subtraction (the difference from subtracting v2 from v1, this should be a numpy array), scale (scalling v1 by a, this should be a numpy array), dot (dot product of v1 and v2, this should be a float), length (norm of v1, this should be a float), and cross (cross product of v1 and v2, this should be a numpy array).

In [31]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
a = 5

com_add = np.add(v1, v2)
com_sub = np.subtract(v1, v2)
com_scale = v1 * a
com_dot = np.dot(v1, v2)
com_length = np.linalg.norm(v1)
com_cross = np.cross(v1, v2)
res = {'addition':com_add , 'substraction':com_sub, 'scale':com_scale, 'dot':com_dot, 'length':com_length, 'cross':com_cross}
res

{'addition': array([5, 7, 9]),
 'substraction': array([-3, -3, -3]),
 'scale': array([ 5, 10, 15]),
 'dot': 32,
 'length': 3.7416573867739413,
 'cross': array([-3,  6, -3])}

1.2 [1 pt] What is the dimension of v3? Please store the v3 dimension into variable v3_dimen using numpy.

For grading purposes, v2_dimen should be type tuple.

In [ ]:
v3 = np.array([5, 4])
v3_dimen= v3.shape
v3_dimen

In [32]:
v4 = np.array([1,  2,  3, 4, 5])

v4_dimen= v4.shape
v4_dimen

(5,)

In [ ]:
added= ['5 * a + 3 * b', '11']

In [45]:
def Matrices(A,B):
    m_add = np.add(A, B)
    m_sub = np.subtract(A, B)
    m_mul = np.dot(A, B)
    m_ele_mul = np.multiply(A, B)
    res = {'addition':m_add , 'substraction':m_sub, 'multiplication':m_mul, 'elementwise':m_ele_mul}
    #raise NotImplementedError()
    return res

In [48]:
A = np.array([-2,6,8,5,-2,8,2,1,4])
B = np.array([10,-4,6,1,8,-3,8,-2,4])
ANS22 = Matrices(A,B)

In [49]:
ANS22

{'addition': array([ 8,  2, 14,  6,  6,  5, 10, -1,  8]),
 'substraction': array([-12,  10,   2,   4, -10,  11,  -6,   3,   0]),
 'multiplication': -1,
 'elementwise': array([-20, -24,  48,   5, -16, -24,  16,  -2,  16])}

In [50]:
C = np.array([[1, 1, 2], [3, 5, 8]])

C_trans=C.T

In [51]:
C_trans

array([[1, 3],
       [1, 5],
       [2, 8]])

In [57]:
C.shape

(2, 3)

In [52]:
D = np.array([[13], [21], [34]])


In [58]:
D.shape

(3, 1)

In [59]:
CD_trans= np.dot(C, D).T

In [56]:
CD_trans

array([[102],
       [416]])

In [60]:
E = np.array([[1, 1, 2], [3, 5, 8], [13, 21, 50]])
E_inv = np.linalg.inv(E)
E_inv 

array([[ 2.5625, -0.25  , -0.0625],
       [-1.4375,  0.75  , -0.0625],
       [-0.0625, -0.25  ,  0.0625]])

In [61]:
BA = Matrices(B,A)['multiplication']
BA_deter = np.linalg.det(BA)

79.99999999999997

In [70]:
A = np.array([[-2,6,8],[5,-2,8],[2,1,4]])
B = np.array([[10,-4,6],[1,8,-3],[8,-2,4]])

trace2A3B = np.add(A*2, B*3).trace()
trace2A3B

66

In [74]:
AB = Matrices(A,B)['multiplication']
AB_trace = AB.T.trace()
AB_trace

23

In [ ]:
𝐹=[[1,2,𝑎],[3,2,1+𝑏],[2,2,2+𝑐]] 
𝐺=[[0,2+𝑐,−𝑎],[3,𝑏+𝑐,−1],[𝑎,3,−𝑏]]
product
[0, 6, -a*b]. [6+2*c, 2*b+2*c, -3*b - b^2], [-a^2, -a, -a*b]

In [ ]:
'''
product of 3x3 matrices

1,2,𝑎
3,2,1+𝑏
2,2,2+𝑐


1(2(2+c) - (1+b)(2)) - 2(3(2+c) - 2(1+b)) + a(3(2) - 2(2))
= 2+2*c+2*b -2 (6 + 3*c - 2 - 2*b) + 2*a
= 2+2*c+2*b - 12 - 6*b + 4 +4*b +2*a
= 2*a+2*c-6  

'''


VALIDATION FAILED ON 4 CELL(S)! If you submit your assignment as it is, you WILL NOT receive full credit.
==========================================================================================
The following cell failed:

1 assert type(Prod_FG) == str, "Problem 3.2, type of value stored in variable Prod_FG does not match the expected type."
* HIDDEN TESTS

The error was:
    ---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-36-6a26ac582827> in <module>
         * HIDDEN TESTS
    
    AssertionError: Problem 3.2, testing Prod_FG, actual vs expected values differ

==
The following cell failed:

1 assert type(Trace_FG) == str, "Problem 3.5, type of value stored in variable Trace_FG does not match the expected type."
* HIDDEN TESTS

The error was:
    ---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-42-459b298ecf38> in <module>
         * HIDDEN TESTS
    
    AssertionError: Problem 3.5, testing Trace_FG, actual vs expected values differ

==========================================================================================
The following cell failed:

1 assert type(Trace_FTGT) == str, "Problem 3.6, type of value stored in variable Trace_FTGT does not match the expected type."
* HIDDEN TESTS

The error was:
    ---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-44-0c6d0941f059> in <module>
         * HIDDEN TESTS
    
    AssertionError: Problem 3.6, string not properly formatted python code or uses undefined vari